export const roxo = "#5A007A"
export const azul = "#3500C7"
export const branco = "#fdfdfd"
export const preto = "#0e0e0e"
export const corBg = "#fdfdfd"
export const fontPrimaria = "'ADLaM Display', cursive"
export const fontSecundaria = "'Permanent Marker', cursive"
